services:
  postgres:
    image: postgres:13-bullseye
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: jaffle_shop
      POSTGRES_PASSWORD: jaffle_shop
      POSTGRES_DB: jaffle_shop
    volumes: 
      - pgdata:/var/lib/postgresql/data
      - ./data/db-init-scripts:/docker-entrypoint-initdb.d
      - ./data:/jaffle_shop_data
# need to use volume for pg perms issue. See https://hub.docker.com/_/postgres
volumes:
  pgdata:
    external: true
    name: pgdata
